<?php/** * EMPLEADOS1_MYSQL.class.php *  **/class EMPLEADOS_MYSQL {	public static $DATABASE_NAME = 'posgourmet';	public static $TABLE_NAME = 'empleados1_mysql';public $CONN;	public $CODSIS ;	public $NOMBRES ;	public $APELLIDOS ;	public $CEDULA ;	public $FECHACONT ;	public $HORAINGMA ;	public $HORASAMA ;	public $HORAINGTA ;	public $HORASALTA ;	public $SUELDO ;	public $CLAVEING ;	public $DESPORMIN ;	public $FOTO ;	public $DIALIBRE ;	public $HUELLA ;	public $ID ;function EMPLEADOS_MYSQL($con) {$this->CON=$con;}	function contructor($CODSIS,$NOMBRES,$APELLIDOS,$CEDULA,$FECHACONT,$HORAINGMA,$HORASAMA,$HORAINGTA,$HORASALTA,$SUELDO,$CLAVEING,$DESPORMIN,$FOTO,$DIALIBRE,$HUELLA,$ID){	$this->CODSIS=$CODSIS;	$this->NOMBRES=$NOMBRES;	$this->APELLIDOS=$APELLIDOS;	$this->CEDULA=$CEDULA;	$this->FECHACONT=$FECHACONT;	$this->HORAINGMA=$HORAINGMA;	$this->HORASAMA=$HORASAMA;	$this->HORAINGTA=$HORAINGTA;	$this->HORASALTA=$HORASALTA;	$this->SUELDO=$SUELDO;	$this->CLAVEING=$CLAVEING;	$this->DESPORMIN=$DESPORMIN;	$this->FOTO=$FOTO;	$this->DIALIBRE=$DIALIBRE;	$this->HUELLA=$HUELLA;	$this->ID=$ID;	}function insertar() { $consulta="INSERT INTO(CODSIS,NOMBRES,APELLIDOS,CEDULA,FECHACONT,HORAINGMA,HORASAMA,HORAINGTA,HORASALTA,SUELDO,CLAVEING,DESPORMIN,FOTO,DIALIBRE,HUELLA,ID)values('".$this->CODSIS."','".$this->NOMBRES."','".$this->APELLIDOS."','".$this->CEDULA."','".$this->FECHACONT."','".$this->HORAINGMA."','".$this->HORASAMA."','".$this->HORAINGTA."','".$this->HORASALTA."','".$this->SUELDO."','".$this->CLAVEING."','".$this->DESPORMIN."','".$this->FOTO."','".$this->DIALIBRE."','".$this->HUELLA."','".$this->ID."')"; return $this->CON->manipular($consulta);}function rellenar($resultado){
        if ($resultado->num_rows > 0) {
            $lista=array();
            while($row = $resultado->fetch_assoc()) {	$empleados1_mysql= new EMPLEADOS1_MYSQL("");		$empleados1_mysql->CODSIS=$row["CODSIS"] ==null?"":$row["CODSIS"];		$empleados1_mysql->NOMBRES=$row["NOMBRES"] ==null?"":$row["NOMBRES"];		$empleados1_mysql->APELLIDOS=$row["APELLIDOS"] ==null?"":$row["APELLIDOS"];		$empleados1_mysql->CEDULA=$row["CEDULA"] ==null?"":$row["CEDULA"];		$empleados1_mysql->FECHACONT=$row["FECHACONT"] ==null?"":$row["FECHACONT"];		$empleados1_mysql->HORAINGMA=$row["HORAINGMA"] ==null?"":$row["HORAINGMA"];		$empleados1_mysql->HORASAMA=$row["HORASAMA"] ==null?"":$row["HORASAMA"];		$empleados1_mysql->HORAINGTA=$row["HORAINGTA"] ==null?"":$row["HORAINGTA"];		$empleados1_mysql->HORASALTA=$row["HORASALTA"] ==null?"":$row["HORASALTA"];		$empleados1_mysql->SUELDO=$row["SUELDO"] ==null?"":$row["SUELDO"];		$empleados1_mysql->CLAVEING=$row["CLAVEING"] ==null?"":$row["CLAVEING"];		$empleados1_mysql->DESPORMIN=$row["DESPORMIN"] ==null?"":$row["DESPORMIN"];		$empleados1_mysql->FOTO=$row["FOTO"] ==null?"":$row["FOTO"];		$empleados1_mysql->DIALIBRE=$row["DIALIBRE"] ==null?"":$row["DIALIBRE"];		$empleados1_mysql->HUELLA=$row["HUELLA"] ==null?"":$row["HUELLA"];		$empleados1_mysql->ID=$row["ID"] ==null?"":$row["ID"];		$lista[]=$empleados1_mysql;};	return $lista;}	else{
            return null;
        }}function todo(){
        $consulta="select * from empleados1_mysql";
        $result=$this->CON->consulta($consulta);
        return $this->rellenar($result);
    }function buscarXID($id){
        $consulta="select * from empleados1_mysql where ID=".$id;
        $result=$this->CON->consulta($consulta);
        $empleados1_mysql=$this->rellenar($result);
        if($empleados1_mysql==null){
            return null;
        }
        return $this->rellenar($result);
    }}